require conf/distro/include/qcom-base.inc

#Robotics
require conf/distro/include/qcom-distro-robotics.inc

#SELinux
require conf/distro/include/qcom-distro-selinux.inc

#SOTA
require conf/distro/include/qcom-distro-sota.inc
