# Copyright (c) 2025 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

require conf/distro/qcom-robotics-ros2-jazzy.conf
require conf/distro/qcom-distro-sota.conf