# Copyright (c) 2025 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

require conf/distro/include/qcom-robotics-sdk.inc
require conf/distro/qcom-distro.conf

DISTRO_NAME = "Qualcomm Linux Robotics Reference Distro with ROS"

DISTRO_FEATURES:append = " ros2-jazzy"
